# Generated by Django 5.0 on 2024-06-28 08:37

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=64,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Награда",
                "verbose_name_plural": "Награды",
            },
        ),
        migrations.CreateModel(
            name="BaseArtObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=64,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Основа арт объекта",
                "verbose_name_plural": "Основы арт объекта",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=64,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=64,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Дата создания коллекции",
                    ),
                ),
                (
                    "private",
                    models.BooleanField(
                        default=False, verbose_name="Частная коллекция"
                    ),
                ),
            ],
            options={
                "verbose_name": "Коллекция",
                "verbose_name_plural": "Коллекции",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=64,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цветовая палитра",
                "verbose_name_plural": "цветовые палитры",
            },
        ),
        migrations.CreateModel(
            name="TeachingActivities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Начало",
                    ),
                ),
                (
                    "ended_at",
                    models.DateField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Конец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподавание",
                "verbose_name_plural": "Преподавание",
                "default_related_name": "teaching",
            },
        ),
        migrations.CreateModel(
            name="EducationalInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Название")),
                (
                    "type_ei",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Университет"),
                            (2, "Колледж"),
                            (3, "Школа искусств"),
                            (4, "Курсы"),
                        ],
                        verbose_name="Тип учебного заведения",
                    ),
                ),
                (
                    "city_of_birth",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебное заведение",
                "verbose_name_plural": "Учебные Заведения",
                "default_related_name": "educational_institution",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=64,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанра",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.CreateModel(
            name="MaterialArtObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=64,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал арт объекта",
                "verbose_name_plural": "материалы арт объекта",
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=64,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стиль",
                "verbose_name_plural": "Стили",
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=64, verbose_name="Фамилия")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="О художнике"
                    ),
                ),
                (
                    "sex",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(1, "М"), (2, "Ж")], verbose_name="Пол"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "date_of_death",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Дата смерти",
                    ),
                ),
                (
                    "personal_style",
                    models.BooleanField(
                        default=False, verbose_name="Персональный стиль"
                    ),
                ),
                (
                    "city_of_birth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="city_of_birth",
                        to="core.city",
                        verbose_name="Город рождения",
                    ),
                ),
                (
                    "city_of_living",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="city_of_living",
                        to="core.city",
                        verbose_name="Город проживания",
                    ),
                ),
                (
                    "favorited_by",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Добавили в избранное",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.image",
                        verbose_name="Фото художника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Художник",
                "verbose_name_plural": "Художники",
                "ordering": ("last_name", "first_name"),
                "default_related_name": "artists",
            },
        ),
        migrations.CreateModel(
            name="ArtistSocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(unique=True, verbose_name="Ссылка на аккаунт"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artobjects.artist",
                        verbose_name="Художник",
                    ),
                ),
                (
                    "social_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.socialmedia",
                        verbose_name="Социальная сеть",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть художника",
                "verbose_name_plural": "Социальные сеть художника",
                "default_related_name": "social_medias",
            },
        ),
        migrations.CreateModel(
            name="ArtistAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(limit_value=2024)
                        ],
                        verbose_name="Год",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artobjects.artist",
                        verbose_name="Художник",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artobjects.award",
                        verbose_name="Награда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Награда художника",
                "verbose_name_plural": "Награды художника",
                "default_related_name": "artist_awards",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "teachingactivities_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="artobjects.teachingactivities",
                    ),
                ),
                ("degree", models.CharField(max_length=64, verbose_name="Степень")),
            ],
            options={
                "verbose_name": "Образование",
                "verbose_name_plural": "Образование",
                "default_related_name": "education",
            },
            bases=("artobjects.teachingactivities",),
        ),
        migrations.AddField(
            model_name="teachingactivities",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="artobjects.artist",
                verbose_name="Художник",
            ),
        ),
        migrations.AddField(
            model_name="teachingactivities",
            name="educational_institutions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artobjects.educationalinstitution",
                verbose_name="Учреждение",
            ),
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Название")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Галерея",
                "verbose_name_plural": "Галереи",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArtObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor", models.IntegerField(unique=True, verbose_name="Артикул")),
                ("name", models.CharField(max_length=64, verbose_name="Название")),
                ("date_of_creation", models.DateField(verbose_name="Дата создания")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "В продаже"), (2, "Продана"), (3, "Не продается")],
                        default=(3, "Не продается"),
                        verbose_name="Статус объекта",
                    ),
                ),
                ("width", models.PositiveIntegerField(verbose_name="Ширина объекта")),
                ("height", models.PositiveIntegerField(verbose_name="Высота объекта")),
                (
                    "unique",
                    models.BooleanField(
                        default=False, verbose_name="Уникальная работа"
                    ),
                ),
                (
                    "art_investment",
                    models.BooleanField(
                        default=False, verbose_name="Вклад в искусство"
                    ),
                ),
                (
                    "max_amount",
                    models.IntegerField(
                        default=1, verbose_name="Количество объектов в продаже"
                    ),
                ),
                (
                    "orientation",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Горизонтальная"), (2, "Вертикальная")],
                        verbose_name="Ориентация",
                    ),
                ),
                (
                    "tag_size",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "до 40 см"),
                            (2, "40 - 100 см"),
                            (3, "100 - 160 см"),
                            (4, "более 160 см"),
                        ],
                        verbose_name="Тег размера",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artobjects.artist",
                        verbose_name="Художник",
                    ),
                ),
                (
                    "city_sold",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="city_sold",
                        to="core.city",
                        verbose_name="ID города",
                    ),
                ),
                (
                    "favourited_by",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="ID пользователя"
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="images",
                        to="core.image",
                        verbose_name="Изображения объекта",
                    ),
                ),
                (
                    "main_image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_image",
                        to="core.image",
                        verbose_name="Изображения объекта",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ID пользователя",
                    ),
                ),
                (
                    "base_art_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base",
                        to="artobjects.baseartobject",
                        verbose_name="Основа",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artobjects.category",
                        verbose_name="ID категории",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="artobjects.collection",
                        verbose_name="В коллекции",
                    ),
                ),
                (
                    "colors",
                    models.ManyToManyField(
                        to="artobjects.color", verbose_name="Цветовая гамма"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artobjects.genre",
                        verbose_name="ID жанра",
                    ),
                ),
                (
                    "material_art_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material",
                        to="artobjects.materialartobject",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artobjects.style",
                        verbose_name="Стиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Артобъект",
                "verbose_name_plural": "Артобъекты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "artobject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artobjects.artobject",
                        verbose_name="Арт объект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена объекта",
                "verbose_name_plural": "История цен объектов",
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Название")),
                (
                    "started_at",
                    models.DateField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Начало",
                    ),
                ),
                (
                    "ended_at",
                    models.DateField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Конец",
                    ),
                ),
                (
                    "personal",
                    models.BooleanField(default=False, verbose_name="Персональная"),
                ),
                (
                    "artobject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artobjects.artobject",
                        verbose_name="Арт объект",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="artobjects.gallery",
                        verbose_name="ID галереи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выставка",
                "verbose_name_plural": "Выставки",
                "ordering": ["name"],
            },
        ),
    ]
