# Generated by Django 5.0 on 2024-07-01 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artobjects", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="show",
            options={
                "default_related_name": "shows",
                "ordering": ["name"],
                "verbose_name": "Выставка",
                "verbose_name_plural": "Выставки",
            },
        ),
        migrations.AlterField(
            model_name="artist",
            name="city_of_birth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artists_hometown",
                to="core.city",
                verbose_name="Город рождения",
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="city_of_living",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="city_of_living",
                to="core.city",
                verbose_name="artists_living_city",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="base_art_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="artobjects.baseartobject",
                verbose_name="Основа",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="city_sold",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artobjects",
                to="core.city",
                verbose_name="ID города",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="favourited_by",
            field=models.ManyToManyField(
                related_name="favorite_artobjects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="images",
            field=models.ManyToManyField(
                blank=True, to="core.image", verbose_name="Изображения объекта"
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artobjects_as_main_image",
                to="core.image",
                verbose_name="Изображения объекта",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="material_art_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="artobjects.materialartobject",
                verbose_name="Материал",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="own_artobjects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="artobjects.gallery",
                verbose_name="ID галереи",
            ),
        ),
    ]
