# Generated by Django 5.0 on 2024-06-30 17:19
# Category(4), Genre(8), Style(18), Color(7),
# MaterialArtObject(10), BaseArtObject()
from django.db import migrations


def add_data(apps, schema_editor):
    Category = apps.get_model("artobjects", "Category")
    data = [
        {
            'id': 1,
            'name': 'живопись',
        },
        {
            'id': 2,
            'name': 'графика'
        },
        {
            'id': 3,
            'name': 'фотография'
        },
        {
            'id': 4,
            'name': 'digital'
        },
    ]
    for row in data:
        Category.objects.update_or_create(**row)

    Genre = apps.get_model("artobjects", "Genre")
    data = [
        {
            'id': 1,
            'name': 'портрет',
        },
        {
            'id': 2,
            'name': 'пейзаж'
        },
        {
            'id': 3,
            'name': 'натюрморт'
        },
        {
            'id': 4,
            'name': 'марина'
        },
        {
            'id': 5,
            'name': 'исторический'
        },
        {
            'id': 6,
            'name': 'батальный'
        },
        {
            'id': 7,
            'name': 'анималистика'
        },
        {
            'id': 8,
            'name': 'ню'
        },
    ]
    for row in data:
        Genre.objects.update_or_create(**row)

    Style = apps.get_model("artobjects", "Style")
    data = [
        {
            'id': 1,
            'name': 'готика',
        },
        {
            'id': 2,
            'name': 'ренессанс'
        },
        {
            'id': 3,
            'name': 'барокко'
        },
        {
            'id': 4,
            'name': 'экспрессионизм'
        },
        {
            'id': 5,
            'name': 'абстракционизм'
        },
        {
            'id': 6,
            'name': 'классицизм'
        },
        {
            'id': 7,
            'name': 'импрессионизм'
        },
        {
            'id': 8,
            'name': 'кубизм'
        },
        {
            'id': 9,
            'name': 'реализм'
        },
        {
            'id': 10,
            'name': 'сюрреализм'
        },
        {
            'id': 11,
            'name': 'поп-арт'
        },
        {
            'id': 12,
            'name': 'романтизм'
        },
        {
            'id': 13,
            'name': 'неоклассицизм'
        },
        {
            'id': 14,
            'name': 'концептуальное искусство'
        },
        {
            'id': 15,
            'name': 'арт-деко'
        },
        {
            'id': 16,
            'name': 'конструктивизм'
        },
        {
            'id': 17,
            'name': 'постмодернизм'
        },
        {
            'id': 18,
            'name': 'стрит-арт'
        }
    ]
    for row in data:
        Style.objects.update_or_create(**row)

    Color = apps.get_model("artobjects", "Color")
    data = [
        {
            'id': 1,
            'name': 'светлые оттенки',
        },
        {
            'id': 2,
            'name': 'темные оттенки'
        },
        {
            'id': 3,
            'name': 'яркие оттенки'
        },
        {
            'id': 4,
            'name': 'теплая цветовая гамма'
        },
        {
            'id': 5,
            'name': 'холодная цветовая гамма'
        },
        {
            'id': 6,
            'name': 'бледные оттенки'
        },
        {
            'id': 7,
            'name': 'ч/б'
        },
    ]
    for row in data:
        Color.objects.update_or_create(**row)

    MaterialArtObject = apps.get_model("artobjects", "MaterialArtObject")
    data = [
        {
            'id': 1,
            'name': 'масло',
        },
        {
            'id': 2,
            'name': 'акварель'
        },
        {
            'id': 3,
            'name': 'акрил'
        },
        {
            'id': 4,
            'name': 'пастель'
        },
        {
            'id': 5,
            'name': 'гуашь'
        },
        {
            'id': 6,
            'name': 'офорт'
        },
        {
            'id': 7,
            'name': 'чернила'
        },
        {
            'id': 8,
            'name': 'карандаш'
        },
        {
            'id': 9,
            'name': 'цифровая печать'
        },
        {
            'id': 10,
            'name': 'смешанная техника'
        },
    ]
    for row in data:
        MaterialArtObject.objects.update_or_create(**row)

    BaseArtObject = apps.get_model("artobjects", "BaseArtObject")
    data = [
        {
            'id': 1,
            'name': 'холст',
        },
        {
            'id': 2,
            'name': 'картон'
        },
        {
            'id': 3,
            'name': 'бумага'
        },
        {
            'id': 4,
            'name': 'дерево'
        },
        {
            'id': 5,
            'name': 'фотобумага'
        },
    ]
    for row in data:
        BaseArtObject.objects.update_or_create(**row)

    Award = apps.get_model("artobjects", "Award")
    data = [
        {
            'id': 1,
            'name': 'Звезда Художественного Мира',
        },
        {
            'id': 2,
            'name': 'Лучшая природная живопись'
        },
        {
            'id': 3,
            'name': 'Нереальное реальное'
        },
        {
            'id': 4,
            'name': 'Звезда Творчества'
        },
    ]
    for row in data:
        Award.objects.update_or_create(**row)


class Migration(migrations.Migration):
    dependencies = [
        ("artobjects", "0002_alter_show_options_alter_artist_city_of_birth_and_more"),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
