# Generated by Django 5.0 on 2024-07-01 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artobjects", "0003_data_of_directories"),
        ("core", "0003_alter_country_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artistsocialmedia",
            options={
                "default_related_name": "artist_social_medias",
                "verbose_name": "Социальная сеть художника",
                "verbose_name_plural": "Социальные сеть художника",
            },
        ),
        migrations.AlterModelOptions(
            name="artobject",
            options={
                "default_related_name": "artobjects",
                "ordering": ["name"],
                "verbose_name": "Артобъект",
                "verbose_name_plural": "Артобъекты",
            },
        ),
        migrations.AlterModelOptions(
            name="educationalinstitution",
            options={
                "default_related_name": "educational_institutions",
                "verbose_name": "Учебное заведение",
                "verbose_name_plural": "Учебные Заведения",
            },
        ),
        migrations.RenameField(
            model_name="educationalinstitution",
            old_name="city_of_birth",
            new_name="city",
        ),
        migrations.AlterField(
            model_name="artobject",
            name="city_sold",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.city",
                verbose_name="ID города",
            ),
        ),
    ]
