# Generated by Django 5.0 on 2024-07-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artobjects", "0004_alter_artistsocialmedia_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={
                "default_related_name": "prices",
                "verbose_name": "Цена объекта",
                "verbose_name_plural": "История цен объектов",
            },
        ),
        migrations.AddField(
            model_name="artobject",
            name="actual_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Цена"
            ),
        ),
    ]
