# Generated by Django 5.0 on 2024-07-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artobjects", "0005_alter_price_options_artobject_actual_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="artobject",
        ),
        migrations.AddField(
            model_name="show",
            name="artobjects",
            field=models.ManyToManyField(
                blank=True, to="artobjects.artobject", verbose_name="Артобъекты"
            ),
        ),
    ]
