# Generated by Django 5.0 on 2024-07-03 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artobjects", "0006_remove_show_artobject_show_artobjects"),
        ("core", "0003_alter_country_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="city_of_living",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="city_of_living",
                to="core.city",
                verbose_name="Город проживания",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="artobjects.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="city_sold",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.city",
                verbose_name="Город прибывания",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="colors",
            field=models.ManyToManyField(
                to="artobjects.color", verbose_name="Цветовые гаммы"
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="favourited_by",
            field=models.ManyToManyField(
                related_name="favorite_artobjects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Добавили в избранное",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="artobjects.genre",
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artobjects_as_main_image",
                to="core.image",
                verbose_name="Главное изображение объекта",
            ),
        ),
        migrations.AlterField(
            model_name="artobject",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="own_artobjects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец картины",
            ),
        ),
    ]
