# Generated by Django 5.0 on 2024-07-03 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "artobjects",
            "0007_alter_artist_city_of_living_alter_artobject_category_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="artobject",
            name="favourited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_artobjects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Добавили в избранное",
            ),
        ),
    ]
