# Generated by Django 5.0 on 2024-07-02 17:04

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artobjects", "0006_remove_show_artobject_show_artobjects"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_at",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Дата начала подписки",
                    ),
                ),
                (
                    "address_delivery",
                    models.TextField(
                        blank=True, max_length=1024, verbose_name="Адрес доставки"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Корзина"), (2, "Доставка"), (3, "Выполнен")],
                        default=(2, "Доставка"),
                        verbose_name="Статус объекта",
                    ),
                ),
                (
                    "is_payment",
                    models.BooleanField(default=False, verbose_name="Оплата прошла"),
                ),
                (
                    "artobjects",
                    models.ManyToManyField(
                        blank=True, to="artobjects.artobject", verbose_name="Артобъекты"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ID пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупка пользователя",
                "verbose_name_plural": "Покупки пользователя",
                "default_related_name": "shoppingcarts",
            },
        ),
    ]
