# Generated by Django 5.0 on 2024-07-03 04:40

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoppingcart", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "default_related_name": "shoppingcarts",
                "ordering": ["-payment_at"],
                "verbose_name": "Покупка пользователя",
                "verbose_name_plural": "Покупки пользователя",
            },
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="payment_at",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date.today
                    )
                ],
                verbose_name="Дата оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
        ),
    ]
