# Generated by Django 5.0 on 2024-07-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoppingcart", "0002_alter_shoppingcart_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Корзина"), (2, "Доставка"), (3, "Выполнен")],
                default=(1, "Корзина"),
                verbose_name="Статус объекта",
            ),
        ),
    ]
