# Generated by Django 5.0 on 2024-07-03 11:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artobjects", "0008_alter_artobject_favourited_by"),
        ("shoppingcart", "0003_alter_shoppingcart_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppingcart",
            name="artobjects",
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="amount",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="artobject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="artobjects.artobject",
                verbose_name="Артобъект",
            ),
            preserve_default=False,
        ),
    ]
