# Generated by Django 5.0 on 2024-07-03 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artobjects", "0008_alter_artobject_favourited_by"),
        (
            "shoppingcart",
            "0004_remove_shoppingcart_artobjects_shoppingcart_amount_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "artobject"), name="cart_user_artobject"
            ),
        ),
    ]
