# Generated by Django 5.0 on 2024-07-03 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shoppingcart", "0005_shoppingcart_cart_user_artobject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "default_related_name": "shopping_cart",
                "verbose_name": "Покупка пользователя",
                "verbose_name_plural": "Покупки пользователя",
            },
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="address_delivery",
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="is_payment",
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="payment_at",
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="status",
        ),
    ]
