# Generated by Django 5.0 on 2024-07-02 15:45

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                ("info", models.TextField(max_length=1024, verbose_name="Описание")),
                (
                    "period",
                    models.SmallIntegerField(verbose_name="Период подписки в днях"),
                ),
                (
                    "is_actual",
                    models.BooleanField(default=True, verbose_name="Действующий тариф"),
                ),
            ],
            options={
                "verbose_name": "Вид подписки",
                "verbose_name_plural": "Виды подписок",
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Дата начала подписки",
                    ),
                ),
                ("ended_at", models.DateField(verbose_name="Дата начала подписки")),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.subscription",
                        verbose_name="ID подписки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ID пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка пользователя",
                "verbose_name_plural": "Подписки пользователя",
                "default_related_name": "user_subscriptions",
            },
        ),
    ]
