# Generated by Django 5.0 on 2024-07-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="ended_at",
            field=models.DateField(verbose_name="Дата окончания подписки"),
        ),
    ]
