# Generated by Django 5.0 on 2024-07-03 05:42

from django.db import migrations

def add_data(apps, schema_editor):
    Subscription = apps.get_model("analytics", "Subscription")
    data = [
        {
            'id': 1,
            'name': 'Пробный период',
            'info': 'Срок действия подписки 3 дня, доступна аналитика стоимости картин.',
            'price': '999',
            'period': '3',
            'is_actual': True,

        },
        {
            'id': 2,
            'name': 'Базовая',
            'info': 'Срок действия подписки 3 месяца, доступна аналитика стоимости картин, отслеживание стоимости картин',
            'price': '180',
            'period': '3',
            'is_actual': True,

        },
        {
            'id': 3,
            'name': 'Премиум',
            'info': 'Срок действия подписки 6 месяца, доступна аналитика стоимости картин, отслеживание стоимости картин',
            'price': '346',
            'period': '3',
            'is_actual': True,

        },
    ]
    for row in data:
        Subscription.objects.update_or_create(**row)

class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_alter_usersubscription_ended_at"),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
