# Generated by Django 5.0 on 2024-07-01 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_data_of_city_country_socialmedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Страна", "verbose_name_plural": "Страны"},
        ),
    ]
