# Generated by Django 5.0.6 on 2024-07-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_alter_country_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "briefe",
                    models.TextField(
                        help_text="Введите краткое описание статьи",
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите полный текст статьи",
                        verbose_name="Текст статьи",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите город, связанный со статьей",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "thumbnail",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите изображение для миниатюры статьи",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.image",
                        verbose_name="Миниатюра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-created_at"],
            },
        ),
    ]
